# -*- coding: utf-8 -*-
"""Слияние.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkpxY4pMHYeqr74IXf4ep_UNXW3rMQv5
"""

def MergeSortImpl(A):
    if len(A) <= 1:
        return(A)
    left = MergeSortImpl(A[:len(A)//2])
    right = MergeSortImpl(A[len(A)//2:])
    B = []
    L = R =0
    while L <len(left) and R <len(right):
        B.append(left[L]     if left[L] <= right[R] else right[R])
        [L, R] = [L+1, R] if left[L] <= right[R] else [L, R+1]
    for L in range(L, len(left)):
        B.append(left[L])
    for R in range(R, len(right)):
        B.append(right[R])
    return B
print("Введите элементы массива")
a = []
a = input().split()
print("Отсортированный массив")
print(MergeSortImpl(a))