# -*- coding: utf-8 -*-
"""Шейкер.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5T_WrqZ7W7eMY9GYmdUBXFJHua60_QR
"""

def ShakerSort(N):
    left = 1
    right = len(N)
    while left<right:
        for i in range(left, right):
            if N[i] < N[i-1]:
                N[i], N[i-1] = N[i-1], N[i]
            if N[right-i] < N[right-i-1]:
                N[right-i], N[right-i-1] = N[right-i-1], N[right-i]
        left += 1; right -= 1
    return N
print("Введите элементы массива")
a =[]
a = input().split()
print("Отсортированный массив")
print(ShakerSort(a))